import './globals.css'
import { Inter } from 'next/font/google'
import ShellClient from "@/app/Shell.client";
import '@elastic/react-search-ui-views/lib/styles/styles.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <ShellClient>
        {children}
      </ShellClient>
      </body>
    </html>
  )
}
